apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: togglemaster
  labels:
    app: auth
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: togglemaster
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
