apiVersion: v1
kind: Service
metadata:
  name: evaluation
  namespace: togglemaster
  labels:
    app: evaluation
    app.kubernetes.io/name: evaluation
    app.kubernetes.io/part-of: togglemaster
spec:
  type: ClusterIP
  selector:
    app: evaluation
  ports:
    - name: http
      port: 80
      targetPort: 8083
      protocol: TCP
