apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: togglemaster
  labels:
    app: analytics
    version: v1
    app.kubernetes.io/name: analytics
    app.kubernetes.io/part-of: togglemaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: analytics
        version: v1
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: analytics
      containers:
        - name: analytics
          image: REPLACE_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics:v1.0.0-00000000
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          env:
            - name: PORT
              value: "8084"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 3
            periodSeconds: 5
