apiVersion: v1
kind: Service
metadata:
  name: targeting
  namespace: togglemaster
  labels:
    app: targeting
    app.kubernetes.io/name: targeting
    app.kubernetes.io/part-of: togglemaster
spec:
  type: ClusterIP
  selector:
    app: targeting
  ports:
    - name: http
      port: 80
      targetPort: 8082
      protocol: TCP
