apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag
  namespace: togglemaster
  labels:
    app: flag
    version: v1
    app.kubernetes.io/name: flag
    app.kubernetes.io/part-of: togglemaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flag
        version: v1
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: flag
      containers:
        - name: flag
          image: 308603596306.dkr.ecr.us-east-1.amazonaws.com/togglemaster/flag:v1.0.0-856294ff
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: PORT
              value: "8081"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
