apiVersion: v1
kind: Service
metadata:
  name: flag
  namespace: togglemaster
  labels:
    app: flag
    app.kubernetes.io/name: flag
    app.kubernetes.io/part-of: togglemaster
spec:
  type: ClusterIP
  selector:
    app: flag
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
