name: "CI/CD — flag"

on:
  push:
    branches: [main]
    paths:
      - "services/flag/**"
      - ".github/workflows/ci-flag.yml"
      - ".github/workflows/_ci-template.yml"
  pull_request:
    branches: [main]
    paths:
      - "services/flag/**"
      - ".github/workflows/ci-flag.yml"
      - ".github/workflows/_ci-template.yml"

jobs:
  ci:
    uses: ./.github/workflows/_ci-template.yml
    with:
      service: flag
      aws_account_id: "308603596306"
      aws_region: "us-east-1"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
